const stateOptions = [
    { value: "AL", label: "Alabama" },
    { value: "AK", label: "Alaska" }
];

const generoData = [
    { value: "Genero", label: "Genero *" },
    { value: "femenino", label: "Femenino" },
    { value: "masculino", label: "Masculino" },
    { value: "otro", label: "Otro" }
];

const tiposDocumentos = [
    // { value: "tipoDocumento", label: "Ej. Cédula" },
    { value: "CEDULA", label: "Cédula" },
    { value: "DNI", label: "DNI" },
    { value: "Pasaporte", label: "Pasaporte" },
    { value: "L.C", label: "L.C" },
    { value: "L.E", label: "L.E" },
    { value: "Otro", label: "Otro" }
];

const captadores = [
    { value: "captador", label: "Captador" },
    { value: "Captador-1", label: "Captador-1" },
    { value: "Captador-2", label: "Captador-2" },
    { value: "Captador-3", label: "Captador-3" },
    { value: "Captador-4", label: "Captador-4" },
    { value: "Captador-5", label: "Captador-5" },
    { value: "Captador-6", label: "Captador-6" },
    { value: "Captador-7", label: "Captador-7" },
    { value: "Captador-8", label: "Captador-8" },
    { value: "Captador-9", label: "Captador-9" },
    { value: "Captador-10", label: "Captador-10" },
];

const diaData = [
    { value: "Dia", label: "Día" },
    { value: "1", label: "1" },
    { value: "2", label: "2" },
    { value: "3", label: "3" },
    { value: "4", label: "4" },
    { value: "5", label: "5" },
    { value: "6", label: "6" },
    { value: "7", label: "7" },
    { value: "8", label: "8" },
    { value: "9", label: "9" },
    { value: "10", label: "10" },
    { value: "11", label: "11" },
    { value: "12", label: "12" },
    { value: "13", label: "13" },
    { value: "14", label: "14" },
    { value: "15", label: "15" },
    { value: "16", label: "16" },
    { value: "17", label: "17" },
    { value: "18", label: "18" },
    { value: "19", label: "19" },
    { value: "20", label: "20" },
    { value: "21", label: "21" },
    { value: "22", label: "22" },
    { value: "23", label: "23" },
    { value: "24", label: "24" },
    { value: "25", label: "25" },
    { value: "26", label: "26" },
    { value: "27", label: "27" },
    { value: "28", label: "28" },
    { value: "29", label: "29" },
    { value: "30", label: "30" },
    { value: "31", label: "31" }
];

const mesData = [
    { value: "Mes", label: "Mes" },
    { value: "1", label: "ENERO" },
    { value: "2", label: "FEBRERO" },
    { value: "3", label: "MARZO" },
    { value: "4", label: "ABRIL" },
    { value: "5", label: "MAYO" },
    { value: "6", label: "JUNIO" },
    { value: "7", label: "JULIO" },
    { value: "8", label: "AGOSTO" },
    { value: "9", label: "SEPTIEMBRE" },
    { value: "10", label: "OCTUBRE" },
    { value: "11", label: "NOVIEMBRE" },
    { value: "12", label: "DICIEMBRE" }

];

const anioData = [
    { value: "Anio", label: "Año" },
    { value: "1930", label: "1930" },
    { value: "1931", label: "1931" },
    { value: "1932", label: "1932" },
    { value: "1933", label: "1933" },
    { value: "1934", label: "1934" },
    { value: "1935", label: "1935" },
    { value: "1936", label: "1936" },
    { value: "1937", label: "1937" },
    { value: "1938", label: "1938" },
    { value: "1939", label: "1939" },
    { value: "1940", label: "1940" },
    { value: "1941", label: "1941" },
    { value: "1942", label: "1942" },
    { value: "1943", label: "1943" },
    { value: "1944", label: "1944" },
    { value: "1945", label: "1945" },
    { value: "1946", label: "1946" },
    { value: "1947", label: "1947" },
    { value: "1948", label: "1948" },
    { value: "1949", label: "1949" },
    { value: "1950", label: "1950" },
    { value: "1951", label: "1951" },
    { value: "1952", label: "1952" },
    { value: "1953", label: "1953" },
    { value: "1954", label: "1954" },
    { value: "1955", label: "1955" },
    { value: "1956", label: "1956" },
    { value: "1957", label: "1957" },
    { value: "1958", label: "1958" },
    { value: "1959", label: "1959" },
    { value: "1960", label: "1960" },
    { value: "1961", label: "1961" },
    { value: "1962", label: "1962" },
    { value: "1963", label: "1963" },
    { value: "1964", label: "1964" },
    { value: "1965", label: "1965" },
    { value: "1966", label: "1966" },
    { value: "1967", label: "1967" },
    { value: "1968", label: "1968" },
    { value: "1969", label: "1969" },
    { value: "1970", label: "1970" },
    { value: "1971", label: "1971" },
    { value: "1972", label: "1972" },
    { value: "1973", label: "1973" },
    { value: "1974", label: "1974" },
    { value: "1975", label: "1975" },
    { value: "1976", label: "1976" },
    { value: "1977", label: "1977" },
    { value: "1978", label: "1978" },
    { value: "1979", label: "1979" },
    { value: "1980", label: "1980" },
    { value: "1981", label: "1981" },
    { value: "1982", label: "1982" },
    { value: "1983", label: "1983" },
    { value: "1984", label: "1984" },
    { value: "1985", label: "1985" },
    { value: "1986", label: "1986" },
    { value: "1987", label: "1987" },
    { value: "1988", label: "1988" },
    { value: "1989", label: "1989" },
    { value: "1990", label: "1990" },
    { value: "1991", label: "1991" },
    { value: "1992", label: "1992" },
    { value: "1993", label: "1993" },
    { value: "1994", label: "1994" },
    { value: "1995", label: "1995" },
    { value: "1996", label: "1996" },
    { value: "1997", label: "1997" },
    { value: "1998", label: "1998" },
    { value: "1999", label: "1999" },
    { value: "2000", label: "2000" },
    { value: "2001", label: "2001" },
    { value: "2002", label: "2002" },
    { value: "2003", label: "2003" },
    { value: "2004", label: "2004" },
    { value: "2005", label: "2005" },
    { value: "2006", label: "2006" },
    { value: "2007", label: "2007" },
    { value: "2008", label: "2008" },
    { value: "2009", label: "2009" },
    { value: "2010", label: "2010" },
    { value: "2011", label: "2011" },
    { value: "2012", label: "2012" },
    { value: "2013", label: "2013" },
    { value: "2014", label: "2014" },
    { value: "2015", label: "2015" },

];

const aniovencimientoData = [
    { value: "Anio", label: "Año" }, 
    { value: "2021", label: "2021" },
    { value: "2022", label: "2022" },
    { value: "2023", label: "2023" },
    { value: "2024", label: "2025" },
    { value: "2026", label: "2027" },
    { value: "2028", label: "2028" },
    { value: "2029", label: "2029" },
    { value: "2030", label: "2030" },
    { value: "2031", label: "2031" },
    { value: "2032", label: "2032" },
    { value: "2033", label: "2033" },
    { value: "2034", label: "2034" },
    { value: "2035", label: "2035" },
]

const estadocivilData = [
    { value: "estadocivil", label: "Estado Civil" },
    { value: "casado", label: "Casado/a" },
    { value: "soltero", label: "Soltero/a (nunca estuvo casado/a)" },
    { value: "viudo", label: "Viudo/a" },
    { value: "divorciado", label: "Divorciado/a" },
    { value: "convive", label: "Convive con su pareja" }
];

const paisData = [
    { value: "pais", label: "Pais" },
    { value: "Afghanistan", label: "Afghanistan"},
    { value: "Albania", label: "Albania"},
    { value: "Algeria", label: "Algeria"},
    { value: "American Samoa", label: "American Samoa"},
    { value: "Andorra", label: "Andorra"},
    { value: "Angola", label: "Angola"},
    { value: "Anguilla", label: "Anguilla"},
    { value: "Antarctica", label: "Antarctica"},
    { value: "Antigua and Barbuda", label: "Antigua and Barbuda"},
    { value: "Argentina", label: "Argentina"},
    { value: "Armenia", label: "Armenia"},
    { value: "Aruba", label: "Aruba"},
    { value: "Australia", label: "Australia"},
    { value: "Austria", label: "Austria"},
    { value: "Azerbaijan", label: "Azerbaijan"},
    { value: "Bahamas (the)", label: "Bahamas (the)"},
    { value: "Bahrain", label: "Bahrain"},
    { value: "Bangladesh", label: "Bangladesh"},
    { value: "Barbados", label: "Barbados"},
    { value: "Belarus", label: "Belarus"},
    { value: "Belgium", label: "Belgium"},
    { value: "Belize", label: "Belize"},
    { value: "Benin", label: "Benin"},
    { value: "Bermuda", label: "Bermuda"},
    { value: "Bhutan", label: "Bhutan"},
    { value: "Bolivia (Plurinational State of)", label: "Bolivia (Plurinational State of)"},
    { value: "Bonaire, Sint Eustatius and Saba", label: "Bonaire, Sint Eustatius and Saba"},
    { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina"},
    { value: "Botswana", label: "Botswana"},
    { value: "Bouvet Island", label: "Bouvet Island"},
    { value: "Brazil", label: "Brazil"},
    { value: "British Indian Ocean Territory (the)", label: "British Indian Ocean Territory (the)"},
    { value: "Brunei Darussalam", label: "Brunei Darussalam"},
    { value: "Bulgaria", label: "Bulgaria"},
    { value: "Burkina Faso", label: "Burkina Faso"},
    { value: "Burundi", label: "Burundi"},
    { value: "Cabo Verde", label: "Cabo Verde"},
    { value: "Cambodia", label: "Cambodia"},
    { value: "Cameroon", label: "Cameroon"},
    { value: "Canada", label: "Canada"},
    { value: "Cayman Islands (the)", label: "Cayman Islands (the)"},
    { value: "Central African Republic (the)", label: "Central African Republic (the)"},
    { value: "Chad", label: "Chad"},
    { value: "Chile", label: "Chile"},
    { value: "China", label: "China"},
    { value: "Christmas Island", label: "Christmas Island"},
    { value: "Cocos (Keeling) Islands (the)", label: "Cocos (Keeling) Islands (the)"},
    { value: "Colombia", label: "Colombia"},
    { value: "Comoros (the)", label: "Comoros (the)"},
    { value: "Congo (the Democratic Republic of the)", label: "Congo (the Democratic Republic of the)"},
    { value: "Congo (the)", label: "Congo (the)"},
    { value: "Cook Islands (the)", label: "Cook Islands (the)"},
    { value: "Costa Rica", label: "Costa Rica"},
    { value: "Croatia", label: "Croatia"},
    { value: "Cuba", label: "Cuba"},
    { value: "Curaçao", label: "Curaçao"},
    { value: "Cyprus", label: "Cyprus"},
    { value: "Czechia", label: "Czechia"},
    { value: "Côte d'Ivoire", label: "Côte d'Ivoire"},
    { value: "Denmark", label: "Denmark"},
    { value: "Djibouti", label: "Djibouti"},
    { value: "Dominica", label: "Dominica"},
    { value: "Dominican Republic (the)", label: "Dominican Republic (the)"},
    { value: "Ecuador", label: "Ecuador"},
    { value: "Egypt", label: "Egypt"},
    { value: "El Salvador", label: "El Salvador"},
    { value: "Equatorial Guinea", label: "Equatorial Guinea"},
    { value: "Eritrea", label: "Eritrea"},
    { value: "Estonia", label: "Estonia"},
    { value: "Eswatini", label: "Eswatini"},
    { value: "Ethiopia", label: "Ethiopia"},
    { value: "Falkland Islands (the) [Malvinas]", label: "Falkland Islands (the) [Malvinas]"},
    { value: "Faroe Islands (the)", label: "Faroe Islands (the)"},
    { value: "Fiji", label: "Fiji"},
    { value: "Finland", label: "Finland"},
    { value: "France", label: "France"},
    { value: "French Guiana", label: "French Guiana"},
    { value: "French Polynesia", label: "French Polynesia"},
    { value: "French Southern Territories (the)", label: "French Southern Territories (the)"},
    { value: "Gabon", label: "Gabon"},
    { value: "Gambia (the)", label: "Gambia (the)"},
    { value: "Georgia", label: "Georgia"},
    { value: "Germany", label: "Germany"},
    { value: "Ghana", label: "Ghana"},
    { value: "Gibraltar", label: "Gibraltar"},
    { value: "Greece", label: "Greece"},
    { value: "Greenland", label: "Greenland"},
    { value: "Grenada", label: "Grenada"},
    { value: "Guadeloupe", label: "Guadeloupe"},
    { value: "Guam", label: "Guam"},
    { value: "Guatemala", label: "Guatemala"},
    { value: "Guernsey", label: "Guernsey"},
    { value: "Guinea", label: "Guinea"},
    { value: "Guinea-Bissau", label: "Guinea-Bissau"},
    { value: "Guyana", label: "Guyana"},
    { value: "Haiti", label: "Haiti"},
    { value: "Heard Island and McDonald Islands", label: "Heard Island and McDonald Islands"},
    { value: "Holy See (the)", label: "Holy See (the)"},
    { value: "Honduras", label: "Honduras"},
    { value: "Hong Kong", label: "Hong Kong"},
    { value: "Hungary", label: "Hungary"},
    { value: "Iceland", label: "Iceland"},
    { value: "India", label: "India"},
    { value: "Indonesia", label: "Indonesia"},
    { value: "Iran (Islamic Republic of)", label: "Iran (Islamic Republic of)"},
    { value: "Iraq", label: "Iraq"},
    { value: "Ireland", label: "Ireland"},
    { value: "Isle of Man", label: "Isle of Man"},
    { value: "Israel", label: "Israel"},
    { value: "Italy", label: "Italy"},
    { value: "Jamaica", label: "Jamaica"},
    { value: "Japan", label: "Japan"},
    { value: "Jersey", label: "Jersey"},
    { value: "Jordan", label: "Jordan"},
    { value: "Kazakhstan", label: "Kazakhstan"},
    { value: "Kenya", label: "Kenya"},
    { value: "Kiribati", label: "Kiribati"},
    { value: "Korea (the Democratic People's Republic of)", label: "Korea (the Democratic People's Republic of)"},
    { value: "Korea (the Republic of)", label: "Korea (the Republic of)"},
    { value: "Kuwait", label: "Kuwait"},
    { value: "Kyrgyzstan", label: "Kyrgyzstan"},
    { value: "Lao People's Democratic Republic (the)", label: "Lao People's Democratic Republic (the)"},
    { value: "Latvia", label: "Latvia"},
    { value: "Lebanon", label: "Lebanon"},
    { value: "Lesotho", label: "Lesotho"},
    { value: "Liberia", label: "Liberia"},
    { value: "Libya", label: "Libya"},
    { value: "Liechtenstein", label: "Liechtenstein"},
    { value: "Lithuania", label: "Lithuania"},
    { value: "Luxembourg", label: "Luxembourg"},
    { value: "Macao", label: "Macao"},
    { value: "Madagascar", label: "Madagascar"},
    { value: "Malawi", label: "Malawi"},
    { value: "Malaysia", label: "Malaysia"},
    { value: "Maldives", label: "Maldives"},
    { value: "Mali", label: "Mali"},
    { value: "Malta", label: "Malta"},
    { value: "Marshall Islands (the)", label: "Marshall Islands (the)"},
    { value: "Martinique", label: "Martinique"},
    { value: "Mauritania", label: "Mauritania"},
    { value: "Mauritius", label: "Mauritius"},
    { value: "Mayotte", label: "Mayotte"},
    { value: "Mexico", label: "Mexico"},
    { value: "Micronesia (Federated States of)", label: "Micronesia (Federated States of)"},
    { value: "Moldova (the Republic of)", label: "Moldova (the Republic of)"},
    { value: "Monaco", label: "Monaco"},
    { value: "Mongolia", label: "Mongolia"},
    { value: "Montenegro", label: "Montenegro"},
    { value: "Montserrat", label: "Montserrat"},
    { value: "Morocco", label: "Morocco"},
    { value: "Mozambique", label: "Mozambique"},
    { value: "Myanmar", label: "Myanmar"},
    { value: "Namibia", label: "Namibia"},
    { value: "Nauru", label: "Nauru"},
    { value: "Nepal", label: "Nepal"},
    { value: "Netherlands (the)", label: "Netherlands (the)"},
    { value: "New Caledonia", label: "New Caledonia"},
    { value: "New Zealand", label: "New Zealand"},
    { value: "Nicaragua", label: "Nicaragua"},
    { value: "Niger (the)", label: "Niger (the)"},
    { value: "Nigeria", label: "Nigeria"},
    { value: "Niue", label: "Niue"},
    { value: "Norfolk Island", label: "Norfolk Island"},
    { value: "Northern Mariana Islands (the)", label: "Northern Mariana Islands (the)"},
    { value: "Norway", label: "Norway"},
    { value: "Oman", label: "Oman"},
    { value: "Pakistan", label: "Pakistan"},
    { value: "Palau", label: "Palau"},
    { value: "Palestine, State of", label: "Palestine, State of"},
    { value: "Panama", label: "Panama"},
    { value: "Papua New Guinea", label: "Papua New Guinea"},
    { value: "Paraguay", label: "Paraguay"},
    { value: "Peru", label: "Peru"},
    { value: "Philippines (the)", label: "Philippines (the)"},
    { value: "Pitcairn", label: "Pitcairn"},
    { value: "Poland", label: "Poland"},
    { value: "Portugal", label: "Portugal"},
    { value: "Puerto Rico", label: "Puerto Rico"},
    { value: "Qatar", label: "Qatar"},
    { value: "Republic of North Macedonia", label: "Republic of North Macedonia"},
    { value: "Romania", label: "Romania"},
    { value: "Russian Federation (the)", label: "Russian Federation (the)"},
    { value: "Rwanda", label: "Rwanda"},
    { value: "Réunion", label: "Réunion"},
    { value: "Saint Barthélemy", label: "Saint Barthélemy"},
    { value: "Saint Helena, Ascension and Tristan da Cunha", label: "Saint Helena, Ascension and Tristan da Cunha"},
    { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis"},
    { value: "Saint Lucia", label: "Saint Lucia"},
    { value: "Saint Martin (French part)", label: "Saint Martin (French part)"},
    { value: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon"},
    { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines"},
    { value: "Samoa", label: "Samoa"},
    { value: "San Marino", label: "San Marino"},
    { value: "Sao Tome and Principe", label: "Sao Tome and Principe"},
    { value: "Saudi Arabia", label: "Saudi Arabia"},
    { value: "Senegal", label: "Senegal"},
    { value: "Serbia", label: "Serbia"},
    { value: "Seychelles", label: "Seychelles"},
    { value: "Sierra Leone", label: "Sierra Leone"},
    { value: "Singapore", label: "Singapore"},
    { value: "Sint Maarten (Dutch part)", label: "Sint Maarten (Dutch part)"},
    { value: "Slovakia", label: "Slovakia"},
    { value: "Slovenia", label: "Slovenia"},
    { value: "Solomon Islands", label: "Solomon Islands"},
    { value: "Somalia", label: "Somalia"},
    { value: "South Africa", label: "South Africa"},
    { value: "South Georgia and the South Sandwich Islands", label: "South Georgia and the South Sandwich Islands"},
    { value: "South Sudan", label: "South Sudan"},
    { value: "Spain", label: "Spain"},
    { value: "Sri Lanka", label: "Sri Lanka"},
    { value: "Sudan (the)", label: "Sudan (the)"},
    { value: "Suriname", label: "Suriname"},
    { value: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen"},
    { value: "Sweden", label: "Sweden"},
    { value: "Switzerland", label: "Switzerland"},
    { value: "Syrian Arab Republic", label: "Syrian Arab Republic"},
    { value: "Taiwan", label: "Taiwan"},
    { value: "Tajikistan", label: "Tajikistan"},
    { value: "Tanzania, United Republic of", label: "Tanzania, United Republic of"},
    { value: "Thailand", label: "Thailand"},
    { value: "Timor-Leste", label: "Timor-Leste"},
    { value: "Togo", label: "Togo"},
    { value: "Tokelau", label: "Tokelau"},
    { value: "Tonga", label: "Tonga"},
    { value: "Trinidad and Tobago", label: "Trinidad and Tobago"},
    { value: "Tunisia", label: "Tunisia"},
    { value: "Turkey", label: "Turkey"},
    { value: "Turkmenistan", label: "Turkmenistan"},
    { value: "Turks and Caicos Islands (the)", label: "Turks and Caicos Islands (the)"},
    { value: "Tuvalu", label: "Tuvalu"},
    { value: "Uganda", label: "Uganda"},
    { value: "Ukraine", label: "Ukraine"},
    { value: "United Arab Emirates (the)", label: "United Arab Emirates (the)"},
    { value: "United Kingdom of Great Britain and Northern Ireland (the)", label: "United Kingdom of Great Britain and Northern Ireland (the)"},
    { value: "United States Minor Outlying Islands (the)", label: "United States Minor Outlying Islands (the)"},
    { value: "United States of America (the)", label: "United States of America (the)"},
    { value: "Uruguay", label: "Uruguay"},
    { value: "Uzbekistan", label: "Uzbekistan"},
    { value: "Vanuatu", label: "Vanuatu"},
    { value: "Venezuela (Bolivarian Republic of)", label: "Venezuela (Bolivarian Republic of)"},
    { value: "Viet Nam", label: "Viet Nam"},
    { value: "Virgin Islands (British)", label: "Virgin Islands (British)"},
    { value: "Virgin Islands (U.S.)", label: "Virgin Islands (U.S.)"},
    { value: "Wallis and Futuna", label: "Wallis and Futuna"},
    { value: "Western Sahara", label: "Western Sahara"},
    { value: "Yemen", label: "Yemen"},
    { value: "Zambia", label: "Zambia"},
    { value: "Zimbabwe", label: "Zimbabwe"},
    { value: "Åland Islands", label: "Åland Islands"},
]


const provinciaData = [
    { value: "provincia", label: "Provincia *" },
    { value: "BUENOS AIRES", label: "BUENOS AIRES" },
    { value: "CIUDAD DE BUENOS AIRES", label: "CIUDAD DE BUENOS AIRES" },
    { value: "CATAMARCA", label: "CATAMARCA" },
    { value: "CHACO", label: "CHACO" },
    { value: "CHUBUT", label: "CHUBUT" },
    { value: "CORDOBA", label: "CORDOBA" },
    { value: "CORRIENTES", label: "CORRIENTES" },
    { value: "ENTRE RIOS", label: "ENTRE RIOS" },
    { value: "FORMOSA", label: "FORMOSA" },
    { value: "JUJUY", label: "JUJUY" },
    { value: "LA PAMPA", label: "LA PAMPA" },
    { value: "LA RIOJA", label: "LA RIOJA" },
    { value: "MENDOZA", label: "MENDOZA" },
    { value: "MISIONES", label: "MISIONES" },
    { value: "NEUQUEN", label: "NEUQUEN" },
    { value: "RIO NEGRO", label: "RIO NEGRO" },
    { value: "SALTA", label: "SALTA" },
    { value: "SAN JUAN", label: "SAN JUAN" },
    { value: "SAN LUIS", label: "SAN LUIS" },
    { value: "SANTA CRUZ", label: "SANTA CRUZ" },
    { value: "SANTA FE", label: "SANTA FE" },
    { value: "SANTIAGO DEL ESTERO", label: "SANTIAGO DEL ESTERO" },
    { value: "TIERRA DEL FUEGO", label: "TIERRA DEL FUEGO" },
    { value: "TUCUMAN", label: "TUCUMAN" },
    { value: "NO SOY DE ARGENTINA", label: "NO SOY DE ARGENTINA" },
]

const tarjetaData = [
    { value: "tipotarjeta", label: "Tarjeta de crédito *" },
    { value: "Amex", label: "AmEx" },
    { value: "Argencard", label: "Argencard" },
    { value: "Cabal", label: "Cabal" },
    { value: "Diners", label: "Diners" },
    { value: "MasterCard", label: "MasterCard" },
    { value: "Naranja", label: "Naranja" },
    { value: "Visa", label: "Visa" },
    { value: "Cencosud", label: "Cencosud" },
    { value: "CMR", label: "CMR" },
    { value: "MAS", label: "MAS" },
    { value: "Favacard", label: "Favacard" },
    { value: "Patagonia 365", label: "Patagonia 365" },
    { value: "Visa-Shopping", label: "Visa-Shopping" },

    { value: "Otras", label: "Otras" }
]

export {
    stateOptions,
    generoData,
    diaData,
    mesData,
    anioData,
    aniovencimientoData,
    estadocivilData,
    paisData,
    provinciaData,
    tarjetaData,
    tiposDocumentos,
    captadores

}